import { Navbar } from '@/components/web3/Navbar';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Eye } from 'lucide-react';

interface PreviewPageProps {
  params: Promise<{
    taskId: string;
  }>;
}

export default async function PreviewPage({ params }: PreviewPageProps) {
  const { taskId } = await params;
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="max-w-6xl mx-auto px-4 py-8 space-y-8">
        <div className="text-center space-y-4">
          <Badge variant="secondary" className="text-sm">
            <Eye className="mr-2 h-4 w-4" />
            Model Preview
          </Badge>
          <h1 className="text-4xl font-bold bg-gradient-to-r from-violet-600 to-purple-600 bg-clip-text text-transparent">
            3D Model Preview
          </h1>
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Preview 3D model generated by task {taskId}
          </p>
        </div>

        <Card>
          <CardHeader>
            <CardTitle>Preview feature in development</CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-muted-foreground">
              The model preview feature is under development. Stay tuned...
            </p>
            <p className="text-sm text-muted-foreground mt-2">
              Task ID: {taskId}
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
